---

- name: ensure fail2ban is installed
  apt: 
    name: fail2ban 
    state: present 
    update_cache: true
    cache_valid_time: 3600
  become: true
  notify:
    - restart fail2ban

- name: ensure fail2ban is configured
  template: 
    src: '{{ item }}.j2' 
    dest: '/{{ item }}'
  become: true
  with_items:
    - etc/fail2ban/jail.local
    - etc/fail2ban/fail2ban.local
  notify:
    - restart fail2ban

- name: ensure fail2ban starts on a fresh reboot
  service: 
    name: fail2ban 
    state: started 
    enabled: yes
  become: true